apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-demo
  name: backend-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-demo
    spec:
      containers:
      - image: devtraining/backend-challenge:9
        name: backend-demo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-demo